#!/usr/bin/env sh

d=`dirname $_`

if [ "$BROWSER" = "" ]; then
    BROWSER=x-www-browser
fi

BROWSER=`readlink -f $(which $BROWSER)`
bn=`basename $(which $BROWSER)`
if [ "$bn" = "chromium-browser" ] || [ "$bn" = "google-chrome" ] || [ "$bn" = "opera-developer" ] || [ "$bn" = "opera" ]; then
    BROWSER="$BROWSER --allow-file-access-from-files"
fi

if [ -f $d/../share/aude/index.html ]; then
    $BROWSER $d/../share/aude/index.html
elif [ -f $d/index.html ]; then
    $BROWSER $d/index.html
else
    echo "Couldn't find aude's index.html file."
fi
